esphome/esphome-webserver

v2/esp-app.ts
Take base path into account for EventSource, such that ESPHome devices can be reached through reverse proxy using path-prefix.
Use case:
When accessing the ESPHome device from another network through a (reverse-)proxy that uses path prefixes, `/events` cannot be reached. See esphome/issues#3462.
This PR solves that issue by taking the base path of the webpage and prepending that to the `/events` URL if applicable.
=> Proxy friendly `/events` path.

v2/esp-switch.ts
I've found with sub-optimal WiFi that the REST calls from the webserver UI can easily take longer than the 250ms rejection timeout (found values in range of 300 to 450ms on my network).
For most entity types this is no big deal, but in case of the switch this causes toggles in quick succession.
Seeing as on decent networks this timeout should not be reached unless there's an actual communication issue I'm wondering if the value could be increased beyond 500ms though, as that would provide a better margin. Thoughts?
=> increase switch toggle timeout

v2/esp-entity-table.ts
Adds a brightness slider for lights that support it.
I've purposely not touched upon RGB, or color temperature as that seems to require additional data and probably other UI elements than what can be acomplished using sliders.
Should fix issue #15.
Example of added sliders:
=> Add brightness slider for Lights.

v2/esp-app.ts
This change takes the `comment` field passed in the `ping` message, and displays it under the main title `<h1>` in it's own `<h3>` tag. This  comment comes from the `esphome:comment` configuration.
If there is no `esphome:comment` configured, it will not add the `<h3>` tag
Note:
- For this to work, pull request this PR in [esphome](https://github.com/esphome/esphome-frontend) needs to be merged to add the `comment` to the `ping` message: https://github.com/esphome/esphome/pull/4246
- This is backwards compatible, so that if an older version `esphome` instance uses this frontend, it work work as normal.
Example config:
```yaml
esphome:
name: tester-d8407a
comment: This Will appear in the WebConsole's header
esp8266:
board: esp01_1m
logger:
ota:
api:
web_server:
wifi:
ssid: !secret …
```
=> Display the esphome:comment

v2/esp-entity-table.ts
Fixes esphome/issues#4001
Correctly handle assumed_state switches in Web UI.
Requires esphome/esphome#4259.
Note:
Could not find propper symbols for 'on' / 'off' so had to settle for the cross & checkmark emoji, as text in the buttons also does not seem to look right. Open to other suggestions of course! ;)
=> Handle assumed_state switches

v2/esp-entity-table.ts
This is a minor enhancement to hide the Actions column by default unless an entity has actions to control.
This is designed for sensor nodes which have no controllable actions or output, but instead have information to display.
This works well with #28
|Before|After|
|---|---|
| <img width="595" alt="Screen Shot 2023-02-12 at 8 55 06 pm" src="https://user-images.githubusercontent.com/767313/218306942-011de9bd-c589-4443-9db1-efa772c58292.png"> | <img width="597" alt="Screen Shot 2023-02-12 at 9 08 51 pm" src="https://user-images.githubusercontent.com/767313/218307452-0397c5f9-b429-4b07-b0eb-b53c682847c4.png"> |
Loading example of with/without entites with actions (Entity with actions intentionally placed last)
|With Actions|Without Actions|
|---|---|
| <video …
=> Hide the Actions column unless an entity has actions available.

captive-portal/index.html
This warning is not true since 2022.11.0.
_Some components such as Captive Portal, Improv via Serial and Improv via BLE enable the user to send and save Wi-Fi credentials to the device. Beginning in 2022.11.0, as long as no credentials are set in the config file, and firmware is uploaded without erasing the flash (via OTA), the device will keep the saved credentials._
https://esphome.io/components/wifi.html#user-entered-credentials
=> Remove outdated warning

v2/esp-app.ts
This is the Javascript components of https://github.com/esphome/esphome/pull/4419 for https://github.com/esphome/feature-requests/issues/2025
Please see the above PR for notes of how/what/why.
=> Add configuration option to disable the log UI.

v2/esp-entity-table.ts
This PR adds simple support for the mauritskorse text components in the v2 server.  Also, the readme directions did not work, I assume they were typos, and changed them to match the current code.
mauritskorse's PR which adds the components
https://github.com/esphome/esphome/pull/3638
Tested against my forked branch of the text components, as the original appears to have not been updated
in a while and did not seem to like the current PlatformIO S2 toolchain.
https://github.com/EternityForest/esphome/tree/sync-add-text-input-component
=> Support text inputs in the v2 server

v2/esp-entity-table.ts
Similar to https://github.com/esphome/esphome-webserver/pull/44
The number slider and box were not updating to match remote state after manually changing inside the webserver frontend
=> Prefix number value with `.`

packages/v3/vite.config.ts
Restores the compilation of www.js.br files that was inadvertently removed via #54
=> V3: restore brotli (.br) compilation

packages/v3/src/esp-entity-table.ts
- Adheres to number of decimal points ([ref](https://discord.com/channels/429907082951524364/1177062706340171807/1212228469195411476))
- Parses `value` as number or string to match use cases
- Sets default `step` value to pass TS lint
=> Range: adhere to decimal points from number or string

packages/v3/src/css/app.ts, packages/v3/src/esp-app.ts
As mentioned in "V3 fixes and feature requests" #56
> Adjust beating heart to a green dot or only display an offline indicator
This changes the ping/heartbeat/online indicator to be a green dot. I personally still like having some sort of periodic "ping" indicator, so I kept the animation, but it only switches to a more vibrant green and does not scale up like the heart did.
| | Online | Ping | Offline |
|-|-|-|-|
| Dark | ![dark online](https://github.com/esphome/esphome-webserver/assets/706138/ba472632-b256-4f39-8c5c-0a1ee2793a9a) | ![dark ping](https://github.com/esphome/esphome-webserver/assets/706138/6bafdb4c-47b8-48f2-86b2-7656ebbf0330) | ![image](https://github.com/esphome/esphome-webserver/assets/706138/57dbb3b3-18f8-40b2-92d2-de10c65bcd40) |
| Light | ![light …
=> Change online indicator to green dot

packages/v3/src/esp-app.ts
It seems like there can be some confusion (#52) around which file should be picked for OTA updates. This is a sort of RFC helping steer people to the right types of files.
Not sure if this could be inadvertently too restrictive if another tool names or formats them differently. Perhaps it's best to add a note about "Usually has a `.bin` extension" or something.
I tested this on macOS, but need help testing other platforms.
=> Force ota update to application/octet-stream

packages/v2/package.json, packages/v3/package.json, scripts/make_header.sh
This adds a 4th parameter to `make_header.sh` that adds a `USE_WEBSERVER_VERSION` for the given value.
This wraps the `const uint8_t INDEX_GZ[] PROGMEM` in an `#if USE_WEBSERVER_VERSION == $4` so that both versions can be included and the right version will be used based on the `version` specified in the config yaml.
Confirmed this condition gets added to `v2` and `v3` packages, but not `captive_portal`.
This also renames the indexes for `v2` and `v3` to `server_index_v2.h` and `server_index_v3.h` respectively so that it's clearer which versions are being referred to. I can leave this part off but then renaming will be needed when copying it into the `web_server` component in `esphome`.
=> Add version check to make_header.sh

packages/v3/src/css/app.ts, packages/v3/src/css/esp-entity-table.ts, packages/v3/src/esp-range-slider.ts
- Truncate the entity name to prevent overflow into the logs on a long name.
- set min-width for name to 150px
- let silder use the whole space
- increase the size of the entity-table from 500px to 600px
fixes #72, #80
=> v3 Truncate long enity name

packages/v3/src/esp-range-slider.ts
Prevent the display from scolling if you are tring to change the value with a slider. 
The problem is issue #80. Because of that the display on a mobile device will be scrollable side to side which i think should never be the case.
But anyway if it happends, this fix will let the user use the slider and prevent the display from sliding if you touch the slider
=> v3 Silder mobile devices fix

scripts/make_header.sh
As mentioned in https://github.com/esphome/esphome/pull/6563#issuecomment-2071068707
> It could pay to also add #ifdef USE_WEBSERVER_LOCAL into the generated headers which would solve this problem entirely.
This adds that `#ifdef`.
Do we want something similar for `captive_index.h`? If so, I might restructure this script a bit so it takes in the `#ifdef` name directly instead of just adding `USE_WEBSERVER_LOCAL` when a version number is passed.
=> Add #ifdef USE_WEBSERVER_LOCAL to make_header.sh

packages/v3/src/esp-entity-table.ts
Allow the slider on the light control to use `width: 100%`
=> v3 light slider width

packages/v3/src/css/esp-entity-table.ts, packages/v3/src/esp-entity-table.ts
v3 Climate component draft.  Introduces: 
- Up/Down buttons for target temperature(s)
- Better layout of information 
- Support for presets 
- Integration with the graph used for sensors 
It could do with a bit more design work, ideally just needs a little more horizontal space
=> v3 Climate Component

packages/v2/src/esp-entity-table.ts
Add support for datetime-datetime on v2
=> v2 support datetime-datetime

packages/v3/src/esp-entity-table.ts
Since the esp adds a default sorting weight of 50 to all entitys they would not get sorted by the name but instead get sorted by the order the esp send them to the client.
Discord discussion:
https://discordapp.com/channels/429907082951524364/1245646776094949471/1263939557276258415
=> [v3] fix sorting to sort by name if sorting weights ar equal

packages/v3/src/css/app.ts, packages/v3/src/css/esp-entity-table.ts, packages/v3/src/esp-entity-table.ts, packages/v3/src/esp-range-slider.ts
Makes Climate component usable
fixes #63
=> [v3] Climate component

packages/v3/src/esp-entity-table.ts
Allows a entity to be added to the list only if the state event is a `DETAIL_ALL` event.
If we receive more than five `DETAIL_STATE` state events from the same component and never got a `DETAIL_ALL` event we fetch the `DETAIL_ALL` json from the esp.
fixes  #125
needs
https://github.com/esphome/esphome/pull/7531
to be merged first!
```yaml
esphome:
name: sorting-glitch
esp32:
board: esp32dev
wifi:
ssid: !secret wifi_ssid
password: !secret wifi_password
logger:
level: ERROR
web_server:
port: 80
version: 3
button:
- platform: template
name: "My Button"
on_press:
- logger.log: Button Pressed
- platform: template
name: "My-Button-2"
on_press:
- logger.log: Button Pressed
datetime:
- platform: template
id: my_datetime_date
type: date
name: My ate
optimistic: yes
initial_value: "2024-01-30" …
```
=> Only allow `DETAIL_ALL` events to be added into the entity list

packages/v3/src/esp-entity-table.ts
Adds a visual representaion of the state of the cover and lock component
depends on #129 and #133
fixes #60, fixes #61
befor
after
=> [v3] Show state for cover and lock

packages/v3/src/esp-entity-chart.ts
This PR fixes #135.
The css `:host-context(.expanded)` selector is not present neither in Safari nor in Firefox and would not be implemented in the future https://developer.mozilla.org/en-US/docs/Web/CSS/:host-context
Therefore, I propose not so pretty solution which does work in Chrome, Firefox and WebKit browsers as well.
P.S. I am not a frontend developer, any enhancements are appreciated.
=> [v3] Fix of chart resize in Safari and Firefox
